### ISSUE TITLE
error when not all types present

### ISSUE THREAD

**Issue by ChristofferFlensburg** [CuppenResearch/MutationalPatterns#5]
Hi!

I get an error in mut_type_occurences when I give it a vcf with almost only C to T type mutations.

```
> table(get_types(vcfs[[1]]))
C>T T>C 
241   1 

> type_occurences = mut_type_occurences(vcfs[1], ref_genome)
Error in `colnames<-`(`*tmp*`, value = c("C>A", "C>G", "C>T", "T>A", "T>C",  : 
  'names' attribute [8] must be the same length as the vector [4]
```

I think it's due to the assumption that all types are present in the table command at line 52 of mut_type_occurences. If not (as in my case), the counts wont have all 8 entries, which messes up the rbind and then causes an error when the column names are set at line 58.

A fix would involve adding zeroes to the counts that are not present in the table I guess.

Cheers, thanks for easy to use method up to this crash. :)
/Christoffer

**Comment by roelj** [comment]
Hi Christoffer!  Thanks for your elaborate report of this bug.  I think your analysis is right.  I'm attempting to write a fix for it.

Have you worked around it yourself already?

**Comment by ChristofferFlensburg** [comment]
I just skipped that branch of the analysis. It wasn't really the part I was after, so no real hurry for me.

I had the same bug myself in one of my scripts, and I think I fixed it by by adding the required options to the vector, and then subtracting one from the table. Here it'd be something like

counts = table(c('C>A', 'C>G', 'allOtherRequiredColumns', types))
counts = counts - 1

It works, and with pretty few lines of code, but it's not really pretty. You can probably come up with something better. :)

**Comment by roelj** [comment]
I came up with the fix above. Basically adding zeros to the counts that aren't present, as you suggested. Could you test it on your sample(s)?

The code is in the 'bugfixes' branch.

**Comment by ChristofferFlensburg** [comment]
```
> type_occurences = mut_type_occurences(vcfs[1], ref_genome)
> type_occurences
        C>A C>G C>T C>T at CpG C>T other T>A T>C T>G
sib2som   0   0 241        239         2   0   1   0
```
Thanks for that, very quick! :)
